<?php
/**
 * Sage includes
 *
 * The $sage_includes array determines the code library included in your theme.
 * Add or remove files to the array as needed. Supports child theme overrides.
 *
 * Please note that missing files will produce a fatal error.
 *
 * @link https://github.com/roots/sage/pull/1042
 */
$sage_includes = array(
  'lib/utils.php',                      // Utility functions
  'lib/init.php',                       // Initial theme setup and constants
  'lib/wrapper.php',                    // Theme wrapper class
  'lib/conditional-tag-check.php',      // ConditionalTagCheck class
  'lib/config.php',                     // Configuration
  'lib/assets.php',                     // Scripts and stylesheets (Roots based)
  'lib/titles.php',                     // Page titles
  'lib/extras.php',                     // Custom functions
  'lib/scripts.php',                    // Scripts and Stylesheets (Autogenerated)
  'lib/component.php',                  // Use to include backend components
  'lib/routes.php',                     // API Routes
  'templates/sidebar.php',
  'custom-types/modules.php',
  'custom-types/campaign.php',
  'custom-types/research-posts.php',
  'custom-types/formats.php',
  'custom-types/news-articles.php',
  'custom-types/press-releases.php',
  'custom-types/format-group.php',
  'shortcodes/module-render.php',
  'shortcodes/blog-render.php',
  'taxonomies/feature.php',
  'taxonomies/vertical.php',
  'taxonomies/device.php',
  'api/util.php',                       // API utility class.
  'api/gallery.php'
);

foreach ($sage_includes as $file) {
  if (!$filepath = locate_template($file)) {
    trigger_error(sprintf(__('Error locating %s for inclusion', 'sage'), $file), E_USER_ERROR);
  }

  require_once $filepath;
}
unset($file, $filepath);

add_action( 'init', 'my_add_excerpts_to_pages' );
function my_add_excerpts_to_pages() {
  add_post_type_support( 'page', 'excerpt' );
}

function title_filter($where, &$wp_query) {
    global $wpdb;
    if($search_term = $wp_query->get( 'search_title' )) {
        /*using the esc_like() in here instead of other esc_sql()*/
        $search_term = $wpdb->esc_like($search_term);
        $search_term = ' \'%' . $search_term . '%\'';
        $where .= ' AND ' . $wpdb->posts . '.post_title LIKE '.$search_term;
    }
    return $where;
}

/********************************************************/
// Adding Dashicons in WordPress Front-end
/********************************************************/
add_action( 'wp_enqueue_scripts', 'load_dashicons_front_end' );
function load_dashicons_front_end() {
  wp_enqueue_style( 'dashicons' );
}