<?php
/**
 * Scripts and stylesheets autogenerated
 *
 */
function undertone_scripts() {
  // Styles
  wp_enqueue_style('vendor', get_template_directory_uri() . "/dist/css/app.css", false, null);

  // Scripts
  wp_enqueue_script('vendor', get_template_directory_uri() . "/dist/js/vendor.js", array(), null, false);
  wp_enqueue_script('app', get_template_directory_uri() . "/dist/js/app.js", array(), null, false);
  
  // Ajax handler
  wp_localize_script('app', 'ajaxUtil', array( 'url' => admin_url( 'admin-ajax.php' ),
                                                   'nonce' => wp_create_nonce( 'myajax-post-comment-nonce' ) ) );

}
add_action('wp_enqueue_scripts', 'undertone_scripts', 100);
